accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.login_user, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('dashboard/<action>', views.dashboard, name='dashboard'),
    path('add_staff/', views.add_staff, name="add_staff")
]

e_kitchen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('order/',include('order.urls'))
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views


urlpatterns = [
        
        path('take_orders/', views.take_orders, name="take_orders"),
        path('fulfil_orders/<action>/<int:id>', views.fulfil_orders, name="fulfil_orders"),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

"""
The Profile model for tracking the type of user. 
it takes a foreign key of the default User model
"""

class Profile(models.Model):
    USER_CHOICES = (
        ('manager', 'Manager'),
        ('kitchen', 'Kitchen'),
        ('counter', 'Counter')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True, blank=True,)
    user_type = models.CharField(max_length=10, null=True, blank=True,
                              choices=USER_CHOICES, default='counter')
    
    def __str__(self):
        return self.user.username

order/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Order(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('completed', 'Completed'))
    order_code = models.CharField(max_length=250, unique=True,blank=True,null=True)
    details = models.CharField(max_length=250)
    date = models.DateTimeField(auto_now_add=True, blank=True,null=True)
    taken_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,related_name='taken_by')
    fulfilled_by = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True, related_name='fulfilled_by')
    status = models.CharField(max_length=10, null=True, blank=True,
                              choices=STATUS_CHOICES, default='pending')

    def __str__(self):
        return self.order_code

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password','first_name','last_name')
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('__all__')

order/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('__all__')

accounts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .forms import UserForm, UserProfileForm
from django.http import HttpResponseRedirect
from django.urls  import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.exceptions import ImproperlyConfigured
from random import randint
from .utils import require
from order.models import Order


# Create your views here.
def dashboard(request, action):
    order = Order.objects.order_by('-status','date') #Oldest pending orders are shown first
    total_staff = User.objects.count()
    pending_order = order.filter(status = "pending")
    completed_order = order.filter(status = "completed")
    if action == "general":
        general = True
        context = context ={"general":general,"order":order,"total_staff":total_staff, "pending_order":pending_order,"completed_order":completed_order}
    elif action == "manager" and require(request,'manager'):
        manager = True     
        context ={"manager":manager,"total_staff":total_staff, "pending_order":pending_order,"completed_order":completed_order}
    
    elif action == "counter" and require(request, 'counter'):
        counter = True
        context = {"counter":counter,"total_staff":total_staff, "pending_order":pending_order,"completed_order":completed_order}

    elif action == "kitchen" and require(request,'kitchen'):
        kitchen = True
        context ={"kitchen":kitchen,"total_staff":total_staff, "pending_order":pending_order,"completed_order":completed_order}
    else:
        error = True
        context = {"error": error}
    return render(request,'dashboard.html',context)




def add_staff(request):
    manager = True
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            profile_form.save()
            registered = True
            return redirect('dashboard', action='general')
    else:
        profile_form = UserProfileForm()
        user_form = UserForm()
     
    return render(request,'dashboard.html',{'manager':manager,'profile_form':profile_form, 'user_form':user_form})

def login_user(request):
        
    if request.method == 'POST':
            # Gather the username and password provided by the user.
            # This information is obtained from the login form.
            # We use request.POST.get('<variable>') as opposed
            # to request.POST['<variable>'], because the
            # request.POST.get('<variable>') returns None if the
            # value does not exist, while request.POST['<variable>']
            # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                if user.is_superuser:
                    action = 'manager'
                else:
                    try:
                        if user.profile.user_type == 'manager':
                            action = 'manager'
                        elif user.profile.user_type == 'counter':
                            action = 'counter'
                        elif user.profile.user_type == 'kitchen':
                            action = 'kitchen'
                        else:
                            pass
                    except:
                        raise ImproperlyConfigured("Create a profile for the user")
                return redirect('dashboard',action=action)
            else:
                return HttpResponse("Your account is disabled.")
        else:
              # Bad login details were provided. So we can't log the user in.
            form_error= "Invalid login details: {0}, {1}".format(username, password)
            return render(request,'login.html',{'form_error':form_error})
                                # The request is not a HTTP POST, so display the login form.
                                # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'login.html', {})    
    
    

def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return HttpResponseRedirect(reverse('login'))

order/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Order
from .forms import OrderForm
from .utils import generate_order_code

def take_orders(request):
    counter= False
    if request.method == 'POST':
        form = OrderForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=True)
            form.order_code = generate_order_code()
            form.taken_by = request.user
            form.save()
            return redirect('dashboard', action='counter')
        else:
            counter= True
            form = OrderForm()

    else:
        counter= True
        form = OrderForm()
    return render(request,'dashboard.html',{'form':form ,'counter':counter})
          

def fulfil_orders(request, action,id):
    order = get_object_or_404(Order,id=id)
    if action == "fulfil":
        order.status = "completed"
        order.fulfilled_by = request.user
        order.save()
    else:
        pass
    return redirect('dashboard', action='kitchen') 

templates/dashboard.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
{{request.user.username|title}}'s DashBoard
{% endblock%}

 {% block content %}
 <div class="w3-container">
    <div class="w3-row w3-margin-top ">
        <div class="w3-col m2 left-col">
            <div class="w3-container">
            
            <a href="{% url 'dashboard' 'manager' %}" class="{% if manager %}w3-grey{% endif %} w3-btn w3-block w3-container w3-padding-16  w3-round-xxlarge">Manage Staffs</a>
            
            <a href="{% url 'dashboard' 'counter' %}" class="{% if counter %}w3-grey{% endif %} w3-btn w3-block w3-container w3-padding-16  w3-round-xxlarge">Take Orders</a>
            
            <a href="{% url 'dashboard' 'kitchen' %}" class="{% if kitchen %}w3-grey{% endif %} w3-btn w3-block w3-container w3-padding-16  w3-round-xxlarge">Fulfil Orders</a>
            
            <a href="{% url 'dashboard' 'general' %}"class="{% if general %}w3-grey{% endif %} w3-btn w3-block w3-padding-16 w3-container  w3-round-xxlarge">See All Orders</a>
            
            <a href="{% url 'logout' %}" class="w3-btn w3-block w3-padding-16 w3-container w3-round-xxlarge">Sign Out</a>
            
        </div>
        </div>
        <!--Right Column-->
        <div class="w3-col m10 w3-white w3-round-xlarge right-col">
       <!--Name Container-->
        <div class="w3-container">
            <div class="w3-left">
            <p> <b>Hello</b>, {{request.user.get_full_name|title}}</p>
            <p>Today is <b><span id="date"></span></b>. </p>
            </div>
            <div class="w3-right">
               <b> <p>{{request.user.get_full_name|title}} <img class="w3-circle icon" src="{% static 'images/avatar.png' %}" alt="Profile Image"></p></b>
            </div>
        </div>

        <div class="w3-row w3-container">  
  
          
          
            {% if manager %}    
            <!---------------------------------------------------------------[manager]---------->    
            <!--Add A New Staff Form-->

                <div class="w3-container w3-col m9 w3-light-grey w3-padding-16 w3-round-xlarge ">
                    
                    <form action="{% url 'add_staff' %}" method="POST">
                        {% csrf_token %}
                        <h2 class="w3-text-blue">Add A New Staff</h2>
                        {% for field in user_form %}
                        {% if field.errors %} 
                        {% for error in field.errors %}
                        <p class="w3-red w3-round-large w3-button">{{error}}</p>
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                        {% for field in profile_form %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <p class="w3-red w3-round-large w3-button">{{error}}</p>
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                        <p>
                        <input name="first_name" id="id_first_name" type="text" class="w3-input w3-round-xxlarge w3-padding-16 w3-grey" required  placeholder="First Name">
                        </p>
                        <p>
                        <input name="last_name" id="id_last_name" type="text" class="w3-input w3-round-xxlarge w3-padding-16 w3-grey" required  placeholder="Last Name">
                        </p>
                        <p>
                        <input name="username" id="id_username" type="text" class="w3-input w3-round-xxlarge w3-padding-16 w3-grey" required  placeholder="Username">
                        </p>
                        <p>
                        <input name="password" id="id_password" type="password" class="w3-input w3-round-xxlarge w3-padding-16 w3-grey" required  placeholder="password">
                        </p>
                        <p>
                        <input name="email" id="id_email" type="email" class="w3-input w3-round-xxlarge  w3-padding-16 w3-grey" required  placeholder="email">
                        </p>
                        <label for="user_type">Staff Type</label>
                        <p>
                        <select class="w3-input w3-round-xxlarge w3-padding-16 w3-grey" required  name="user_type" id="id_user_type">

                            <option value="manager">Manager</option>

                            <option value="kitchen" selected>Kitchen</option>

                            <option value="counter">Counter</option>

                        </select>
                        </p>
                        <p>
                        <input  type="submit" class="w3-btn w3-round-xxlarge w3-padding-16 w3-blue" value="submit">
                        
                    </form>
                </div>
                {% endif %}



{% if counter %}
<!----------------------------------------------------------[COUNTER/TAKE ORDER]------------------------------------------------>
<div class="w3-container w3-col m9 w3-light-grey w3-padding-16 w3-round-xlarge">
        {{request.user.id|json_script:'user-id'}}

        <form id="OrderForm">
            <p>
                <input name="details" id="id_details" type="text" class="w3-input w3-round-xxlarge w3-padding-16 w3-grey" required  placeholder="Order Details">
            </p>
            <input  id ="submit" type="submit" class="w3-btn w3-round-xxlarge w3-padding-16 w3-blue" value="submit">        
        </form>

        <script> 
            document.querySelector('#submit').onclick = function(e){
                e.preventDefault(); 
                const user_id = JSON.parse(document.getElementById('user-id').textContent);
                const get_order = document.querySelector('#id_details');
                const order = get_order.value;
                takeOrderSocket.send(
                    JSON.stringify({
                        'details': order,
                        'action': 'take_order'
                    })
                );
                document.getElementById('OrderForm').reset();
                window.createNotification({

                        closeOnClick: true,
                        displayCloseButton: true,
                        positionClass:'nfc-top-right',
                        showDuration: 3500,
                        theme:'success'
                })
                ({
                    title:'Success',
                    message:'Order Sent',
                });
            }
            
            const takeOrderSocket = new WebSocket(
                'ws://'+
                window.location.host +
                '/ws/order/'
            );
       
        </script>
 </div>


{% endif %}


{% if kitchen %}
<!----------------------------------------------[Kitchen]------------------------>
 <div class="w3-container w3-col m9 w3-light-grey w3-padding-16 w3-round-xlarge ">
     <div class= "w3-responsive ">
    <table id="order_table"  class="w3-table w3-bordered">

				<thead>
				<tr>
					<th>id</th>
					<th>Order Code</th>
					<th>Details</th>
                    <th>Status</th>
                    <th>Action</th>
				</tr>
				</thead>

				<tbody>


                {% for order in pending_order %}
                <tr>
					<td>{{order.id}}</td>
                    <td>{{order.order_code}}</td>
                    <td>{{order.details}}</td>
                    <td>{{order.status}}</td>
                    <td><a href="{% url 'fulfil_orders' 'fulfil' order.id %}" class="w3-green w3-btn w3-round-xlarge">Fulfil</a> </td>
                    {% empty %}
                    <p>No pending Order....</p>
             
				</tr>
   {% endfor %}
				</tbody>
            </table>
            </div>
 </div>

<script>
    const fulfilSocket = new WebSocket(
        'ws://'+
        window.location.host +
        '/ws/order/'
    );
    
    fulfilSocket.onmessage = function(e){
        const data = JSON.parse(e.data);
        var get_table = document.getElementById('order_table').getElementsByTagName('tbody')[0];

        const app = `<tr>
                        <td>${data.id}</td>
                        <td>${data.order_code}</td>
                        <td>${data.details}</td>
                        <td>${data.status}</td>
                        <td><a href="/order/fulfil_orders/fulfil/${data.id}" class="w3-green w3-btn w3-round-xlarge">Fulfil</a> </td>  
				    </tr>`
        var newRow = get_table.insertRow(get_table.rows.length);
        newRow.innerHTML = app;
        
        /* Update Stats*/
        var get_stat = document.getElementById('pending-stat');
        var stat = parseInt(get_stat.textContent);
        var newStat = stat+1;
        get_stat.innerText = newStat;
        window.createNotification({

            closeOnClick: true,
            displayCloseButton: true,
            positionClass:'nfc-top-right',
            showDuration: 5000,
            theme:'warning'
            })
            ({
            title:'Info',
            message:'New Order',
        });
                    
    }
 </script>
{% endif %}

{% if general %}

<!-----------------------------------[Landing Page]------------------------->
<div class="w3-container w3-col m9 w3-light-grey w3-padding-16 w3-round-xlarge ">
    <div class="w3-responsive">
    <table class=" w3-table w3-bordered">

				<thead>
				<tr>
					<th>id</th>
                    <th>Order Code</th>
                    <th>Date</th>
					<th>Details</th>
                    <th>Status</th>
                    <th>Taken By</th>
                    <th>Fulfilled by</th>
                 
				</tr>
				</thead>

				<tbody>


                {% for order in order %}
                    <tr>
					<td>{{order.id}}</td>
                    <td>{{order.order_code}}</td>
                    <td>{{order.date}}</td>
                    <td>{{order.details}}</td>
                    <td>{{order.status}}</td>
                    <td>{{order.taken_by.username}}</td>
                    <td>{{order.fulfilled_by.username}}</td>
                    
    
                    {% empty %}
                    <p>No Order Yet....</p>
             
				</tr>
   {% endfor %}
				</tbody>
            </table>
            </div>
 </div>

{% endif %}


{% if error %}
        <div class="w3-container w3-col m9  w3-padding-16 w3-round-xlarge ">
            <div class="w3-red w3-round-xlarge w3-padding">
            <b><h2>Access Denied!</h2></b>
            <p>You are not authorized to view this page. Contact the administrator.</p> 
            </div>
        </div>

{% endif %}




















                <div class="w3-container statz  w3-col m2 w3-margin-bottom w3-round-xlarge w3-padding-16 w3-padding-16 w3-blue">
                    <h2>
                        Stats
                    </h2>
                    <p>
                        Staff{{total_staff|pluralize}} <p class="stat">{{total_staff}}</p>
                    </p>
                    <p>
                        Pending Order{{pending_order|pluralize}} <p id ="pending-stat" class="stat">{{pending_order.count}}</p>
                    </p>
                    <p>
                        Completed Order{{completed_order|pluralize}}<p class="stat">{{completed_order.count}}</p>
                    </p>

                </div>
            </div>

        </div>
    </div>

 </div>
 <script>
     var d = new Date()
     document.getElementById('date').innerHTML = d.toDateString();
 </script>
 	
   {% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/w3.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/notifications.css'%}">
	<script src="{% static 'js/notifications.js' %}"></script>
</head>
<body class="w3-light-grey">
    
<header>
	<!--Desktop Header-->
  	<div class="w3-bar w3-blue">
		<button class="logo w3-bar-item w3-btn w3-left">e-Kitchen</button>
	</div>
</header>
<main class="main">
   {% block content %}

   {% endblock %}
</main>
<footer class="footer w3-blue">
	<div class="w3-center">
		<p>Developed by Daystar Dev</p>
	</div>
</footer>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% block title %}Enter Your Login Details{% endblock %}
{% block content %}
<div class="w3-container">
    <form class="w3-white login-form  w3-content w3-cntainer w3-round-large" action="" method="POST">
        {% csrf_token %}
        <h2 class="w3-margin w3-center">Login</h2>
        <div class="w3-container">
            {% if form_error %}
            <p class="w3-container w3-red w3-padding w3-btn w3-round-large">{{form_error}}</p>
            {% endif %}
        <p>
        <input name="username" id="id_username" type="text" class="w3-input w3-round-xxlarge w3-padding-16 w3-grey" placeholder="Username">
        </p>
        <p>
        <input name="password" id="id_password" type="password" class="w3-input w3-round-xxlarge w3-padding-16 w3-grey" placeholder="password">
        </p>
         <p>
        <input  type="submit" class="w3-btn w3-round-xxlarge w3-padding-16 w3-blue" value="submit">
        </p>                        
        </div>      
    </form>

        <h2 id="sock"></h2>
        <script>
            var socket = new WebSocket('ws://localhost:8000/ws/some_url/');
            socket.onmessage = function(event){
                var data = JSON.parse(event.data);
                console.log(data);
                document.querySelector('#sock').innerHTML = data.message;
            }
        </script>

</div>
{% endblock %}